services:
  web:
    build: .
    depends_on:
      - db
    environment:
      POSTGRES_URL: jdbc:postgresql://db:5432/
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "8080:8080"
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
