jakarta.persistence.jdbc.driver=org.postgresql.Driver
jakarta.persistence.jdbc.url=${POSTGRES_URL:jdbc:postgresql://localhost:5432/}
jakarta.persistence.jdbc.user=${POSTGRES_USER:postgres}
jakarta.persistence.jdbc.password=${POSTGRES_PASSWORD:postgres}
hibernate.current_session_context_class=thread
hibernate.show_sql=false